language: ruby
rvm:
- 2.3.1
before_install: bash etc/ci-setup.sh
before_script: bundle exec rake hatchet:setup_travis
script: bundle exec parallel_test test/hatchet -n 9
after_script: bundle exec rake hatchet:teardown_travis
env:
  global:
  - HATCHET_BUILDPACK_BRANCH=master
  - HATCHET_RETRIES=3
  - HATCHET_APP_LIMIT=80
  - secure: KvuEChRTZYrWd1Q4PKt3YM5FkfuCAOtsKgjC4HDGjCYVNee3793XGwAr0e5LiQqrvHDmbJS7ZPelV3ptor2QJTdmZjPhu/tZKPMLQg7wm8vTcrJflkJDqJl6ECxd40zbUgmo+wSPSvx+K3ZGKqLF4D43vvFJaqBUoAVOGdt66c8=
  - secure: XuJ4XUraWzNlfY9a+6Mh9lVlLuRY988YAaA8LKQOe2KAT5MRqcZzqlKOwDeTWK0tas68bzK7T8RT/L+6/nck0u5VrPHMhkc8QDBSqcle8kFcBxf/64EnCzB40lZoxvcdQ3wm8E41DRwsI7hAHLdVVNXC8f1/wQOAm77nOEvPdvM=
sudo: false
dist: trusty
