language: ruby
rvm:
- 2.0.0
before_script: bundle exec rake hatchet:setup_travis
script: bundle exec parallel_test test/hatchet -n 9
after_script: bundle exec rake hatchet:teardown_travis
env:
  global:
  - HATCHET_RETRIES=3
  - HATCHET_APP_LIMIT=80
  - secure: IuwT8MLmcdWIZvuD+XgHE9jh/49NcZ5Q6Wh7M2ROIQPsNjQ9jPHFpTTdL6p0/63eq948WUKrrPqDFRm/jh/JKyJPmQfDgWq4ScoPdurhgLlGg1CH81gi22t9VwO5QeoYLufMyueqazGbQCAl+xsa+hsKcs6nb836yDHsmBud6z0=
