version: 2
references:
  unit: &unit
    run:
      name: Run test suite
      command: PARALLEL_SPLIT_TEST_PROCESSES=25 bundle exec parallel_split_test spec/
  restore: &restore
   restore_cache:
     keys:
       - bundler_deps
  save: &save
   save_cache:
      paths:
        - ./vendor/bundle
      key: bundler_deps
  hatchet_setup: &hatchet_setup
    run:
      name: Hatchet setup
      command: |
        bundle exec hatchet ci:setup
  bundle: &bundle
    run:
      name: install dependencies
      command: |
        bundle install --jobs=4 --retry=3 --path vendor/bundle
        bundle update
        bundle clean

jobs:
  "ruby-2.5":
    docker:
      - image: circleci/ruby:2.5
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *hatchet_setup
      - <<: *unit
      - <<: *save
  "ruby-2.6":
    docker:
      - image: circleci/ruby:2.6
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *hatchet_setup
      - <<: *unit
      - <<: *save
  "ruby-2.7":
    docker:
      - image: circleci/ruby:2.7
    steps:
      - checkout
      - <<: *restore
      - <<: *bundle
      - <<: *hatchet_setup
      - <<: *unit
      - <<: *save

workflows:
  version: 2
  build:
    jobs:
      - "ruby-2.5"
      - "ruby-2.6"
      - "ruby-2.7"
